### ISSUE TITLE
when the code is available?

### ISSUE THREAD

**Issue by redorangeyellowy** [lixiny/ArtiBoost#2]
I was very impressed by the excellent research.

By any chance, could you tell me when the learning code and the CCV generation code will be released?

**Comment by lixiny** [comment]
Hi, Thanks for your interest in our work! :smile:
I have released the pretrained models and evaluation cods for HO3Dv2, v3, and DexYCB datasets.  You can check the latest README for more details. 
As for the training and pre-processing codes, you should be able to see them by November this year.
Hope this helps!

Best,
Lixin
